version: '3.9'

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        RELEASE_VERSION: 10.1.0
    links:
      - db:database
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    environment:
        ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
        ETHEREUM_JSONRPC_TRACE_URL: http://host.docker.internal:8545/
        ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8546/
        CHAIN_ID: '173'

  visualizer:
    extends:
      file: ./services/visualizer.yml
      service: visualizer
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

  # Disabled sig-provider service as looking up for function/event signatures might cause timeout on logs and internal transaction tab/page.
  #sig-provider:
  #  extends:
  #    file: ./services/sig-provider.yml
  #    service: sig-provider
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-size: "500m"
  #      max-file: "2"

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

  user-ops-indexer:
    depends_on:
      - db
      - backend
    extends:
      file: ./services/user-ops-indexer.yml
      service: user-ops-indexer
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/nginx.yml
      service: proxy
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
