version: '3.9'

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 6.6.0
    links:
      - db:database

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend

  proxy:
    depends_on:
      - backend
      - frontend
    extends:
      file: ./services/nginx.yml
      service: proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.blockscout.rule=Host(`scan.eniac.network`)
      - traefik.http.routers.blockscout.entrypoints=web-secure
      - traefik.http.routers.blockscout.tls=true
      - traefik.http.routers.blockscout.tls.certresolver=letsencrypt-tls
      - traefik.http.services.blockscout.loadbalancer.server.port=80
